/**
 * Build `.dev.vars` for local development from `.env.dev`.
 *
 * `.dev.vars` is a generated artifact: edit `.env.dev` (copy `.env.dev.example` to create it),
 * never `.dev.vars` itself. With `--watch`, edits to `.env.dev` are rebuilt into `.dev.vars` while
 * a dev server is running, and both `@cloudflare/vite-plugin` and `wrangler dev` reload the worker
 * when that file changes — no restart needed.
 *
 * Layering, last wins (wrangler parses with dotenv, so a later line overrides an earlier one):
 *   1. `.env.dev`
 *   2. `.dev.vars.local`, git-ignored per-developer overrides (optional)
 */
import { spawn } from 'node:child_process'
import { existsSync, readFileSync, watch, writeFileSync } from 'node:fs'

const HEADER = '# GENERATED by scripts/dev-vars.mjs (pnpm dev-vars). Edit .env.dev or .dev.vars.local.'

/** Write `.dev.vars`: the env file, plus the per-developer overrides. */
function build(sourcePath, outPath) {
  if (!existsSync(sourcePath)) {
    // Loud rather than a silent empty file: absent vars fail in confusing ways later.
    console.error(`[dev-vars] missing ${sourcePath}: copy .env.dev.example to .env.dev`)
    process.exit(1)
  }

  const source = readFileSync(sourcePath, 'utf8')
  const parts = [source]
  if (existsSync('.dev.vars.local')) parts.push(readFileSync('.dev.vars.local', 'utf8'))

  writeFileSync(outPath, `${HEADER}\n${parts.join('\n')}\n`, 'utf8')
  console.log(`[dev-vars] wrote ${outPath} from ${sourcePath}`)
}

/** Source files whose edits should reach a running dev server. */
const WATCHED = ['.env.dev', '.dev.vars.local']

/**
 * Rebuild `.dev.vars` whenever a source file changes.
 *
 * Watches the DIRECTORY, not the files: editors save atomically (write a temp file, rename over the
 * original), which breaks a watch held on the original inode.
 */
function startWatching(rebuild) {
  let timer
  watch('.', { persistent: true }, (_event, filename) => {
    if (!filename || !WATCHED.includes(filename)) return
    // Debounced: one save can emit several events, and a rename arrives as two.
    clearTimeout(timer)
    timer = setTimeout(() => {
      try {
        rebuild()
      } catch (err) {
        // Never take the dev server down over a half-written file; the next save fixes it.
        console.error(`[dev-vars] rebuild failed: ${err.message}`)
      }
    }, 50)
  })
  console.log(`[dev-vars] watching ${WATCHED.join(', ')}`)
}

// Running as a script (not being imported by a test).
if (process.argv[1]?.endsWith('dev-vars.mjs')) {
  const args = process.argv.slice(2)
  // Everything after `--` is the dev command to run under the watcher.
  const dashDash = args.indexOf('--')
  const command = dashDash === -1 ? [] : args.slice(dashDash + 1)

  const rebuild = () => build('.env.dev', '.dev.vars')
  rebuild()

  if (args.includes('--watch')) startWatching(rebuild)

  if (command.length > 0) {
    // The watcher lives and dies with the dev server it was started for, so no orphan is left
    // rewriting .dev.vars after you have moved on.
    const child = spawn(command[0], command.slice(1), { stdio: 'inherit', shell: false })
    for (const signal of ['SIGINT', 'SIGTERM']) {
      process.on(signal, () => child.kill(signal))
    }
    child.on('exit', (code, signal) => process.exit(signal ? 1 : code ?? 0))
  }
}
